### ISSUE TITLE
Show option for setting content public

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1216]
We need an option for an author to make content public, which would presumably go into Assignment Settings for now.

We have two flags that should be exposed to the UI:
* isPublic: content can be viewed by anyone, even without logging in (currently through the /public endpoint).
* userCanViewSource: those who can view content can also view the DoenetML.  Currently, only implemented in conjunction with isPublic to allow the DoenetML to be viewed in the Guest Editor.

**Comment by Lyanthropos** [comment]
@dqnykamp My understanding is that this would be added to the bottom of the assignment settings panel, correct?

**Comment by Lyanthropos** [comment]
I'm also assuming that the correct permission checks are:
 - isPublic: `canPublishContent`
 - userCanViewSource: `canEditContent` (unless we add `canModifyActivitySettings`)
 -

**Comment by dqnykamp** [comment]
> @dqnykamp My understanding is that this would be added to the bottom of the assignment settings panel, correct?

Yes, that seems like a reasonable place.
