### ISSUE TITLE
Enrollment list not updated after enrolling students

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1245]
Steps to reproduce the bug.

In a new course, click the Import CSV file button from the Import Learners menu.  After accepting the enrollment of the students, the enrollment screen still says there are no students currently enrolled.  Navigating away and returning to the enrollment screen also does not reveal the students.  Refreshing the page shows the students just enrolled.

**Comment by kevincharles** [comment]
I'm currently tracking this down.
