### ISSUE TITLE
Undefined behavior when both owner and student in course

### ISSUE THREAD

**Issue by clary149** [Doenet/DoenetTools#1281]
Both courses appear at the beginning. When the student course is opened, content appears as owner. After that only the owner card appears in table. Virginia may be able to give more details.

**Comment by dqnykamp** [comment]
Question: why do we allow someone to be both owner and student?  I'm not sure what this is useful for.  If one is an owner, they can switch to "student view" to view the course as a student.  If an owner really wanted to act like a student, I'd think they'd make another account.

Besides this being confusing, I'm not sure how the data generated by the owner account acting like a student would be distinguished from the same userId taking the course as a student.

**Comment by kevincharles** [comment]
This is no longer an issue as you can now only have one role in the course
