### ISSUE TITLE
Feature Request: add a 'copyToClipboard' button for DoenetML source code

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1351]
Button for Hello World Examples allowing users to copy DoenetML source code by clicking on a button in the browser rather than cut and paste from the editor pane.

**Comment by virginiaMae** [comment]
please include as an option within the existing `<callAction>` component, in the actionName attribute. Please call this actionName "copyToClipboard". The action should copy all of the content existing within a target sectional component, so everything contained within a `<p>`, a `<pre>`, or a `<div>` for example.

**Comment by dqnykamp** [comment]
If you interact with the content before calling this action, should the copied DoenetML reflect the new state of the system or the original values?  (I may end up doing whichever I can figure out how to do, but in case either way seems an option....)

**Comment by dqnykamp** [comment]
I'm going for the original DoenetML, at least for now.  That's much easier as I can grab it from the DoenetML passed into core rather than trying to recreate DoenetML from components themselves.

**Comment by virginiaMae** [comment]
agreed. I think it should reflect the original state
