### ISSUE TITLE
identicalAxisScales broken in <graph>

### ISSUE THREAD

**Issue by rogness** [Doenet/DoenetTools#1354]
Submitted issues as requested for things that came up at the Doenet Authoring meeting:

Minimal (not) Working Example:

    <graph xmin="-1" xmax="1" ymin="-1" ymax="1" width="100%" identicalAxisScales="true" />

The width="100%" attribute doesn't change the height, which messes up the aspect ratio and results in different scales on the axes.  (We talked about potentially having a "scale" attribute which would scale both the width and the height, or having a "size" attribute which could range from tiny to large, but that's a separate issue.)  Setting identicalAxisScales="true" does not fix the aspect ratio, and totally overrides the min and max values for the axes.  In the code above, the x-axis runs from -40 to 40, and the y-axis from 0 to 45.  Duane asked me to submit the issue so that identicalAxisScales could be fixed, regardless of what we do about the size / aspect ratio.

**Comment by rogness** [comment]
Agreed.  If I do

    <graph xmin="-1" xmax="1" ymin="-1" ymax="2" identicalAxisScales="true" />

then the y-axis stays the same, xmax is changed to 2, and the graph is square.  Similarly, 

    <graph xmin="-1" xmax="1" ymin="-1" ymax="2" width="700" identicalAxisScales="true" />

keeps the y-axis unchanged, and stretches out the x-axis from -2 to 6.  The graph isn't square anymore, but the axes scales are the same.

**Comment by dqnykamp** [comment]
Source of bug is the identical scales code interpreting width="100%" as width="100px", so it thinks it is a tall graph.  Rather than try to fix it in the current framework, I'm planning to remove the height attribute and replace it with an aspect ratio attribute.  I think that will lead to behavior closer to what is expected.
