### ISSUE TITLE
graph tag positioning

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1365]
As illustrated by the below DoenetML, the position of a graph is a little off.  In a sideBySide, it overlaps with items to the right.  It looks like it is shifted to the right a little bit.

```
<sideBySide>
<lorem generateParagraphs="1"/>
<graph width="100%">
  <point />
</graph>
<lorem generateParagraphs="1"/>
</sideBySide>

<graph width="100%">
  <point />
</graph>
<lorem generateParagraphs="1"/>
```

**Comment by rogness** [comment]
I don't know if this is related, but graphs appear to have more padding or indentation on the left than other components, which could account for why things are overlapping on the right.  In the code below, the title, text (whether inside a paragraph tag or not) and the tabular environment all line up on the left, but the graph is indented a bit.

    <title>Example</title>
    <p><lorem generateWords="20" /></p>
    Text
    <graph width="300"><point>(0,0)</point></graph>
    <tabular width="300">
        <row bottom="major"><cell /></row>
        <row bottom="major"><cell>This tabular component is the same width as the graph.</cell></row>
    </tabular>
