### ISSUE TITLE
feature request: graphical implementation of "degrees" and "radians" attributes of angle component

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1381]
Graphically render angles of a specified "degrees" or "radians" when combined with a line or a point using the "betweenLines" or the "through" attributes.  Users can define an angle of a certain measure but, currently, there does not seem to be a  way to actually render an angle of a specified measure  on a given line within a graph without determining additional geometry (other throughpoints or lines)

**Comment by dqnykamp** [comment]
#1389 makes <angle> always create three points if it can.  This means it will display on a graph.

The algorithm follows the Doenet principle of just making a reasonable guess if underdetermined.  With no information, it creates the angle off the positive x-axis.  With a single point, it creates an angle from the ray from the origin to that point.  With two points is creates an angle from the ray starting at the second point in the direction of the first point (which is a breaking change from previous behavior).  With a single line, it finds the point on the line closest to the origin and uses that for the angle vertex.

In all these cases, it first checks for radians, else it checks for degrees, else it uses a right angle.

I hope this works for how you want to use it.
