### ISSUE TITLE
Boolean input display problem with full checkwork button

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1576]
If adding a full checkwork button to a boolean input, the checkwork button overlaps with the checkbox.

`<answer type="boolean" forceFullCheckworkButton>true</answer>`

**Comment by dqnykamp** [comment]
I added a kludge to the label of the boolean input, hard coding a left margin of 8px to give it some space.  Presumably, if this spacing bug is fixed properly, that kludge can be removed.

**Comment by keaganeng** [comment]
Awaiting PR: https://github.com/Doenet/DoenetTools/pull/1606
