### ISSUE TITLE
BUG: Unable to change the name of an activity 

### ISSUE THREAD

**Issue by Abdulkhan2002** [Doenet/DoenetTools#1596]
When trying to rename an activity by clicking on an already created activity, gets an error stating "cannot set properties of undefined (setting 'isOpen)

**Comment by kevincharles** [comment]
I'm not able to reproduce this locally or on production.  Could you find the conditions which I could use to reproduce the bug?

**Comment by kevincharles** [comment]
Was a localhost issue.  Not a bug.
