### ISSUE TITLE
Adjust input and checkwork button spacing

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1612]
Right now, \<matrixInput> puts a lot of spacing between the boxes.  Can the spacing be reduced somewhat to make a more compact display?

**Comment by kevincharles** [comment]
Duane can we get some doenetML code that would show the different possibilities the UI should cover?

**Comment by dqnykamp** [comment]
`<matrixInput />`
or
`<matrixInput numRows="2" numColumns="2" />`

We don't need all that space around the mathquill boxes.  C.f.

`<m>\begin{bmatrix}1 & 2\\3 & 4\end{bmatrix}</m>`

for how latex renders a matrix.

**Comment by keaganeng** [comment]
matrixInput uses a mathInput for each entry, which is why there is 12px of space around each entry. If I change matrixInput, it will put inconsistent spacing around mathInput. There are 12px right and bottom margins on all DoenetML components. How should I proceed? @dqnykamp @kevincharles 
![Screen Shot 2022-10-06 at 3 00 59 PM](https://user-images.githubusercontent.com/72275793/194333112-a3ca3c43-5a7e-41ca-ae6d-9d2230093bf3.png)

**Comment by dqnykamp** [comment]
Is there a good reason for having this spacing around each mathinput? 

For example, for the DoenetML `<answer>x</answer>` or `<answer type="text">hello</answer>`, I always found the extra space between the input and the checkwork button somewhat bothersome.

But, what is really bad with mathinput spacing is if you want to put mathinputs in a sentence.  For example, this looks quite bad.
```
<p>The answers are <mathinput />, <mathinput/>, and <mathinput />.</p>
```
![image](https://user-images.githubusercontent.com/1037056/194365054-e24b7165-42e1-4f86-9432-8ae3efce4fb2.png)

Having the commas and period floating so far away from the mathinput makes the sentence structure hard to see.  The large spacing to the right seems undesirable to me.  Reducing vertical spacing seems like a good idea to me, too, so that the lines aren't so far apart in a paragraph with mathinputs on each line.

I'm all for removing spacing around mathinputs, unless there's some case that I'm missing where we want such spacing.

**Comment by keaganeng** [comment]
I see your point about mathInputs being used in paragraphs. It all comes down to consistency-- we have 12px margins around all renderers, both with and without the checkWorkButton. If we reduce mathInput's margins, would we reduce the margins for all input renderers? And, how much of a margin would you rather see (for both right and bottom margins)?

**Comment by keaganeng** [comment]
<img width="847" alt="Screen Shot 2022-10-07 at 1 23 56 AM" src="https://user-images.githubusercontent.com/72275793/194441322-f59afdb6-7cb0-4ebf-9bce-bde72e929b21.png">
If we were to only adjust mathInput's margins, here is an example of how the components would look with inconsistent spacing.

**Comment by dqnykamp** [comment]
It makes sense to have smaller and consistent spacing on mathinput, textinput, booleaninput, and the inline version of choiceinput.  Then, the checkwork buttons would be closer in
```
<p><answer>x</answer> <answer type="text">hello</answer>
<answer inline><choice credit="1">a</choice><choice>b</choice></answer>
<answer type="boolean">true</answer></p>
```
and we could use them all in a sentence.
```
<p>We have a <mathinput />, a <textinput/>,
a <choiceinput inline ><choice>this</choice><choice>that</choice></choiceinput>,
a <booleaninput />, and others.</p>
```

I'd bring the space down as low as you can get without it looking bad.  For the above sentence to work, we'd like the commas to be closer to the inputs at the left than the word at the right, so the spacing should be smaller than the space between words.  If the commas nearly touched the inputs, that'd be fine, as long as one could notice the commas.

I'm not sure if there are other design considerations for other places where the inputs would be used.  I'm OK if the checkwork buttons touch or nearly touch the inputs unless that just looks bad.  The closeness of the checkwork button makes is clear that the checkwork is just for the adjacent input.

I'm no expert in design; I'm just thinking of the functionality.

**Comment by keaganeng** [comment]
In progress fixes: #1709 
@dqnykamp, what do you think of this amount of spacing? I've reduced the right margin by half (from 12px to 6px). Please let me know your thoughts before I continue.
<img width="1047" alt="Screen Shot 2022-10-12 at 10 41 41 AM" src="https://user-images.githubusercontent.com/72275793/195308898-c806a161-9ba2-49e5-9ce3-dac74e25a8fe.png">

**Comment by keaganeng** [comment]
After my 1-1 meeting with Kevin, we reduced the right margin on the input tags even further, from 6px to 4px. I was thinking we would keep the 12px right margin on the checkWorkButton. Please let me know your thoughts.
<img width="1386" alt="Screen Shot 2022-10-12 at 3 09 46 PM" src="https://user-images.githubusercontent.com/72275793/195365795-9f3cb648-ccdb-481b-99b8-96083c818a98.png">

**Comment by dqnykamp** [comment]
The small space without the checkwork buttons looks good.  Can we also decrease the space to the right of the checkwork buttons, or is there a case where we need it?  In the sentence with the commas, we don't want the space, even with the checkwork buttons.  If we have a bunch a row, as in the first line, we probably want space to make it clear the association of the button.  But, if for some reason, and author wants those in a a row like that, they could just add space via DoenetML, such as using a <nbsp/> or putting them in a <table>.  We don't have a DoenetML tag to take away space.

**Comment by keaganeng** [comment]
Sounds good. I have reduced the right margin of the checkWorkButton to 4px like the other input tags. I have also adjusted matrixInput to have a 4px right margin, which was your original request. I have kept the bottom margins of all components (except mathInput, due to its nesting in matrixInput) to 12px -- is this ok?

Please let me know your thoughts now.
<img width="1049" alt="Screen Shot 2022-10-13 at 10 53 19 AM" src="https://user-images.githubusercontent.com/72275793/195565433-e0c50767-5a68-43a6-87b2-27dd3ad2f5a2.png">

**Comment by dqnykamp** [comment]
This looks great, thanks!

If we could also reduce the bottom margin, that'd be better.  Take a look at this DoenetML where the inputs are in paragraphs.
```
<p><lorem generateSentences="10" /> <mathinput />
  <lorem generateSentences="10" /></p>
<p><lorem generateSentences="10" /> <textinput />
  <lorem generateSentences="10" /></p>
<p><lorem generateSentences="10" /> <choiceinput inline />
  <lorem generateSentences="10" /></p>
<p><lorem generateSentences="10" /> <booleaninput />
  <lorem generateSentences="10" /></p>
```
Because of the extra space, it looks like 7 paragraphs rather than 4.  With the exception of `<booleanInput>`, the extra space makes it look like a paragraph break.  If we can reduce the bottom spacing to minimize the gap, I think it would be an improvement.

**Comment by dqnykamp** [comment]
Also, FYI, if you edit the description of PR #1709 to include "Fixes #1612", then it will link the issue and the PR.

**Comment by dqnykamp** [comment]
These changes broke the answer-button for a block choiceinput answer:
```
<answer><choice credit="1">correct</choice><choice>incorrect</choice></answer>
```
![image](https://user-images.githubusercontent.com/1037056/195597342-23ed6bc3-d74c-440c-b6c7-dc3ce7049b59.png)

Also, check out out cases with a full checkwork button, as the words now look a little squished without spacing around them.
```
<answer forceFullCheckworkButton>x</answer>
<answer forceFullCheckworkButton type="text">hello</answer>
```

**Comment by keaganeng** [comment]
Ok. I've reduced the bottom margin on input tags to also be 4px, so that both the right and bottom margins are now 4px. I believe I've corrected the broken answer button for choiceInput and the squished words on fullCheckWorkButton. Please let me know your thoughts.
<img width="881" alt="Screen Shot 2022-10-14 at 12 17 50 PM" src="https://user-images.githubusercontent.com/72275793/195834516-bbcf29d1-1ba1-413a-a2c4-69de0da2bbb3.png">
<img width="439" alt="Screen Shot 2022-10-14 at 12 18 02 PM" src="https://user-images.githubusercontent.com/72275793/195834546-0ac4d8a6-fe08-4afe-8dfe-e108f009653b.png">

**Comment by dqnykamp** [comment]
Looks great!

I found one small inconsistency.  The size of checkwork, correct, etc. buttons on an inline choiceinput are a slightly different size than the others, and they are slightly different sizes among them so that the text to the right shifts when you click the checkwork button.

I didn't check the partial credit and response submitted buttons, but make sure all 5 buttons are consistent for all the different examples, with and without forceFullCheckworkButton.

**Comment by keaganeng** [comment]
I think I've fixed the inline choiceInput checkWork button, but could you please provide me some sample code to test the 5 different types of buttons? 

Do you want the fullCheckWork button to remain the same size at all times? Right now, it changes size and shifts the right text after being clicked because the word "Incorrect" is shorter than "Check Work".
<img width="335" alt="Screen Shot 2022-10-17 at 10 13 28 AM" src="https://user-images.githubusercontent.com/72275793/196138659-2dc660c2-77fa-45c6-8aa7-b8719bf95313.png">

**Comment by dqnykamp** [comment]
The choiceinput button spacing looks good.

To get the partial credit buttons, you have to use the form with an `<award>` and add an `<award credit="0.5" >` or with some other fraction credit.  The "50%" button is going to be wider than the others, so we'll just have put up with text shifting.

To get the response submitted buttons, as the flag `showCorrectness="false"` to each `<answer>`.

I think it is OK if the width changes with the full checkwork buttons.

Here are some partial credit examples.  (Not sure why would one have partial credit with a boolean, but one could make DoenetML like this.)
```
<answer>
  <award>x</award>
  <award credit="0.5">y</award>
</answer>
<answer type="text">
  <award>hello</award>
  <award credit="0.5">bye</award>
</answer>
<answer inline>
  <choice credit="1">correct</choice>
  <choice credit="0.5">partial</choice>
  <choice>incorrect</choice>
</answer>
<answer type="boolean">
  <award>true</award>
  <award credit="0.5">false</award>
</answer>
```
