### ISSUE TITLE
Numbers selected for a variant change when add additional components

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1615]
For a given variant, numbers selected from, for example, a \<selectFromSequence>, change when one adds seemingly unrelated components.  For example, given this DoenetML
```
<selectFromSequence length="1000" />
```
the selected number will change if add
```
<solution>hi</solution>
```
This is presumably caused by creating an additional call to the rng before the selection is made.  Is this OK behavior?  It certainly confused me as I didn't expect the selection to change as I was working on a document and not changing anything with a select.  Not sure how this could be avoided.

**Comment by kevincharles** [comment]
I agree, it's weird and unexpected.
