### ISSUE TITLE
<answer> with nested <choice> components or with attribute type="text" has outdated button styling

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1645]
Reference image:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/91755591/191562673-515adc0b-d62b-4999-92ef-1cf2121c63ad.png">

source file from Hello World:
https://www.doenet.org/public?tool=editor&doenetId=_KUEAHUTRPwYATqcM4PLjb

**Comment by keaganeng** [comment]
Is this still an issue? When I open the [source file](https://www.doenet.org/public?tool=editor&doenetId=_KUEAHUTRPwYATqcM4PLjb) provided above, I see this styling:
<img width="553" alt="Screen Shot 2022-10-05 at 11 38 50 AM" src="https://user-images.githubusercontent.com/72275793/194041549-93b56328-c3f6-484c-b866-5a20aa4f2e7d.png">

**Comment by kevincharles** [comment]
Looks like this is finished.
