### ISSUE TITLE
Bug: Students are able to access people tab 

### ISSUE THREAD

**Issue by ernzher** [Doenet/DoenetTools#1653]
When view as student, user should not be able to access people tab and change the people settings

**Comment by Lyanthropos** [comment]
Where are you able to see this? Production does not produce this behavior on a student profile at the moment... but that does not mean a regression that has not been merged has not occurred.

The visibility should be based on `canManageUsers`, you can test the flag in `Dashboard.jsx`

**Comment by kevincharles** [comment]
This is fixed
