### ISSUE TITLE
<md> styling change request - additional space for readability between <mrow>s

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1738]
Add some additional space/breathing room between consecutive <mrow>s in an <md> block. For rational algebraic expressions, the multiple lines become hard to read.  See example below of congestion between the two lines of math.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/91755591/196716505-94757a73-0f39-468c-ab14-5e46944efdc9.png">

**Comment by dqnykamp** [comment]
The vertical spacing of `<md>` is determined by how MathJax renders a `\begin{align*}line 1\\line2\end{align*}`.  It's not something we control specifically from our own styling.

We *could* change the `\\` to something like `\\[5px]` to force MathJax to add extra spacing (assuming it follows that latex convention), but I'm not inclined to start seconding guessing MathJax or trying to figure out under what conditions we should add extra spacing.

I'm going to close this as "wontfix," but am open to discussing this further if there is interest in a way to force more spacing.
