### ISSUE TITLE
remove redundant subscript key from math keyboard QWERTY emulator

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1739]
The subscript key is already in the math keyboard "xy" menu, and the key in the QWERTY emulator should be removed for clarity. From authoring meeting 10/19

**Comment by virginiaMae** [comment]
Here is the subscript key I was referring to. You click on the ABC button in the lower right corner of the keyboard.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/91755591/204886525-4538f869-9a7d-4922-b04e-ba56f4bdee24.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/91755591/204886321-6036e706-3dae-4ca8-9220-b04414d66175.png">

**Comment by dqnykamp** [comment]
Fixed by #1948
