### ISSUE TITLE
Bug: navigation with back button fails to return to courses page

### ISSUE THREAD

**Issue by jaltekruse** [Doenet/DoenetTools#1745]
Seems pretty reproducible for me, I'm on chrome on Ubuntu.

https://user-images.githubusercontent.com/365366/197059871-2bb1f625-a5db-4e00-a3d2-b1a4ff58322a.mp4

**Comment by jaltekruse** [comment]
I also just tried not navigating as far down, it appears selecting a course and immediately hitting the back button also reproduces this.

**Comment by dqnykamp** [comment]
Duplicate of #1637
