### ISSUE TITLE
Fix or remove the ) key from math keyboard

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1750]
The ")" key on the math keyboard is currently simply an alias for the right arrow key.

It is true that the right arrow key will move to the right of the ")" and effectively close it if you only type simpler characters and don't move after typing the "(".  However, in general, it will not close the parentheses so it is misleading to have the behavior.

The correct behavior is what typing the ")" on the regular keyboard accomplishes.  If mathQuill has not yet finalized the right ")" of a recent "(", i.e., the ")" is still gray, then pressing ")" moves the right ")" to the current location.  If there is no unmatched "(" to the left, then it creates a "(" to match the ")" one is creating at the current location.

I was unable to reproduce this behavior programmatically.  Trying "cmd", "write" or "type" with ")" first finalized the grayed out ")" to the right, then created a ")" at the current location along with a new "(" to the left.  I did not dig further to determine the cause, in particular if this behavior is caused by some feature of our environment or if it is just the behavior of the mathQuill API.

If we cannot fix the behavior of the ")" key, then I think it would be better to remove it from the keyboard.

**Comment by keaganeng** [comment]
@dqnykamp Do you happen to have a screenshot of this issue?

**Comment by dqnykamp** [comment]
Here's an example showing what the ")" should do and what it currently does.  I type "(x+y+z" then hit the left arrow.  In the first example, I then press ")" on the physical keyboard, giving the correct expression "(x+y)+z".  In the second example, I press the ")" on the virtual keyboard, which just moves the cursor right a character.

The problem is that these commands first finalize the ")" all the way on the right.  (It turns from gray to black.)  So even if the ")" key sends the ")", it does not do what the physical keyboard does.

[Screencast.webm](https://user-images.githubusercontent.com/1037056/200078869-22bb360a-628f-43dc-9159-2b556075bc37.webm)

**Comment by keaganeng** [comment]
Thanks for clarifying. I took a look at https://www.desmos.com/calculator, which also uses mathQuill in the keyboard: https://www.desmos.com/api/v0.3/docs/index.html#document-mathquill. Their keyboard does not seem to have an issue with ")". So I think we might be able to fix this with some digging around...

**Comment by dqnykamp** [comment]
Good to hear!

**Comment by dqnykamp** [comment]
Fixed by #1948
