### ISSUE TITLE
feature request: add textBox and imageBox as graphical components

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1751]

**Comment by dqnykamp** [comment]
I'm thinking of allowing `<text>`, `<math>`, `<m>`, `<label>` (for text combined with math), and `<image />` to be added inside a `<graph>`.  Should we also allow `<me>` and `<md>`?

**Comment by virginiaMae** [comment]
Yes. That would be great!

**Comment by dqnykamp** [comment]
Here's my current idea for positioning:

- Attribute `anchor` is a point giving the coordinates of the anchor used to specify the location of the object on the graph (defaults to (0,0)).
- Attribute `anchorPosition` specifies the position of the anchor relative to the item.  It is one of `top`, `bottom`, `left`, `right`, `center`, `upperRight`, `upperLeft`, `lowerRight`, `lowerLeft`.  The default is `upperLeft`.  (Hope the term `anchorPosition` isn't confused with the anchor coordinates specified by the `anchor` attribute.)
- If the attribute `draggable` is true and `fixed` is false (the defaults), then when you drag the item, the anchor point is moved and the position relative to the anchor remains fixed.
