### ISSUE TITLE
bug: inconsistent definition of what it means to be signed in

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1789]
For AccountSettings, being signed in means that, not only do you have a userId from a JWT, but also that the userId must exist in the user table.

For HomePanel, being signed just means that you have a JWT_JS cookie.

This means, that you could be signed in as far as the HomePanel is concerned, but not signed in as far as AccountSettings is concerned.  In this case (which is happening to me now), AccountSetting says you need to log in, but the link to log in says that you are already looged in!  Confusing behavior from which there is no way to escape short of deleting your cookies.

We need a consistent definition of what is means to be logged in.  Presumably, we should have a utility function or a recoil atom that is used everywhere.

**Comment by kevincharles** [comment]
This should be fixed with the next roll out.  The stored sign in cookie is the true definition of signed in.
