### ISSUE TITLE
Bug: points styled as cross and plus are invisible with default styling

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1791]
The cross at (1,0) and plus at (2,0) are invisible unless you hover over them with a mouse.
```
<setup>
  <styledefinitions>
    <styledefinition stylenumber="1" markerStyle="cross" />
    <styledefinition stylenumber="2" markerStyle="plus" />
  </styledefinitions>
</setup>

<graph>
  <point x="1" />
  <point styleNumber="2" x="2" />
</graph>
```

**Comment by dqnykamp** [comment]
I'm not sure how we should deal with `SVs.open` for these markers.  Do we just always treat them as open so that the stroke color is specified?  (To modify the `open` state variable, you can use an `<endpoint>`, which has an `open` attribute.)

**Comment by keaganeng** [comment]
Can you please explain how `<styledefinition />` is supposed to work? I don't understand why these two examples render differently (even though the second example shows points, it still seems incorrect to me:
<img width="1101" alt="Screen Shot 2022-11-18 at 10 39 01 AM" src="https://user-images.githubusercontent.com/72275793/202684427-8a3a19a1-d30d-4146-849e-7ec84bc4dda7.png">
<img width="1100" alt="Screen Shot 2022-11-18 at 10 39 33 AM" src="https://user-images.githubusercontent.com/72275793/202684622-761a83e1-7715-427a-b40a-fae2e457e808.png">

**Comment by dqnykamp** [comment]
In the first example, you are changing style numbers 1 and 2, and then plotting points using style numbers 1 and 2, which then take on the new attributes.  The points are a cross and a plus (which are currently styled to be invisible except if you highlight them by hovering over them).

In the second example, you are changing style numbers 3 and 4, and then plotting points using style numbers 1 and 2.  Since you haven't changed style numbers 1 and 2, the points use their default style (as defined in style.js).  If you plotted points with style numbers 3 and 4, they should be a cross and a plus (but invisible).

The attribute `styleNumber` of `<styleDefinition>` behaves differently than the other attributes in that is specifies which style number we are changing.  I am inferring from your question that the behavior of that attribute may be confusing, but I'm not sure how to change it.
