### ISSUE TITLE
<answer> component crashes Doenet when entered into the <codeEditor/> component

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1864]

**Comment by dqnykamp** [comment]
Can you give an example of how to trigger this crash?  I created a `<codeEditor showResults />`, typed an `<answer>x</answer>` into the code editor and was able to get a functioning answer blank.

**Comment by dqnykamp** [comment]
Since we redid in #2120 the code viewer attached to the code editor, I imagine this bug doesn't exist anymore.  Please reopen if this is a problem.
