### ISSUE TITLE
Bug: gradebook download is broken

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#1876]
Clicking the "Download CSV" in the gradebook does nothing but show an error in the console. 

It looks like GradeDownload.jsx has not been updated to the new db structure, as it is referring to driveId.

**Comment by Lyanthropos** [comment]
This is correct. Downloads was deemed out of scope during the last gradebook update. Should be a relatively simple upgrade to preform if it is now needed

**Comment by dqnykamp** [comment]
Yep, it's that time of year!
