### ISSUE TITLE
feature request - way to display very large mathematical text for activities for younger grades

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1916]
First priority would be a way to do this in a `<p>`  or a `<text>` component outside a graph. Next, would be a way to do this for a `<text> `or a `<label>` element within a graph.

**Comment by dqnykamp** [comment]
Is this a setting particular to these DoenetML components?  Or is this just a global zoom feature, like one would get if they zoomed in with the browser?

**Comment by virginiaMae** [comment]
Perhaps it is both. If an author wanted all `<p>` tags in a document to appear large, it would get tedious to add an attribute to all of them. I think there should be an attribute to enlarge individual components, as well as an attribute to specify at the document level if desired.

**Comment by virginiaMae** [comment]
Closing this issue due to a suitable latex workaround 
use the `\huge` style specification within a display math or a latex-formatted math.
