### ISSUE TITLE
feature request - elements manually styled as "black" with custom styleDefinitions automatically get updated to "white" in dark mode

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1918]

**Comment by dqnykamp** [comment]
We can't do this switch just in the renderers (like all other dark mode settings).  We'd need to pump the dark mode setting into core because <copy prop="styleDescription" /> must also switch to saying "white" when dark mode is activated.

**Comment by virginiaMae** [comment]
If adding the feature is problematic, perhaps we can issue a warning to users when styleDefinitions are created with color attributes that will not appear in dark mode?

**Comment by dqnykamp** [comment]
Of course, the reverse is true.  An author could be working in dark mode and create something with the color "white".  Then it would be invisible in regular mode.... But, if we made "black" be "white" and "white" be "black" in dark mode, then an author creating something with the color "white" would see it end up being black and invisible.

**Comment by dqnykamp** [comment]
Here's the solution I'm leaning toward: for each color/colorWord style attribute, add a companion attribute with the same name appended by "DarkMode", which would represent the color when dark mode is activated.  If a dark mode color is not specified, then the dark mode color would match the regular color.  In the default styles, we'd make anything that is black be white in dark mode, and vice-versa.  It will be up to authors when defining their styleDefinitions to adjust for dark mode.  Maybe we can issue a warning for colors that won't appear, either white in regular model or black in dark mode.
