### ISSUE TITLE
feature request: graph attribute to reverse the positive direction of the x-axis or y-axis

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1940]
Arose while working with stress-strain diagrams, where positive shear is downward...

**Comment by dqnykamp** [comment]
Apparently, this feature already exists.  Simply make xmax smaller than xmin, and the direction of the x-axis is reversed.  This DoenetML reverses the direction of both axes.

```
<graph xmin="10" xmax="-10" ymin="10" ymax="-10">
```
