### ISSUE TITLE
Need to design system for surfacing errors/warnings to doenetML authors alongside other renderable content

### ISSUE THREAD

**Issue by jaltekruse** [Doenet/DoenetTools#1956]
@dqnykamp had some early work he did using the new Rust based core code, where he added a new renderer for an error message that can exist in a document.

We also need to have a product discussion about how permissive we want to be, should we have a difference between an error and a warning? Should there be minor structural problems that allow and we only show warnings about them in a little notification area, but don't render ugly messages into the rendered doc?

**Comment by dqnykamp** [comment]
Fixed by #2288
