### ISSUE TITLE
bug in graph component with x-axis labelling arbitrarily switching to scientific notation

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1988]
this seems to occur in an intermediate range of the x-axis (not at zero) and at a scale with tick mark labels spaced around 1 - 2 integers apart.
See linked example.
https://www.doenet.org/public?tool=editor&doenetId=_66nLMjr8fza5j1zn40bJR

**Comment by dqnykamp** [comment]
When I upgraded locally to the development version of jsxgraph, then this bug goes away.  So, I'm hopeful this will be resolved when jsxgraph releases a new version.
