### ISSUE TITLE
Forcing reload of renderers when updating server

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#2093]
The DoenetML renderers are loaded dynamically based on the ones needed for a particular DoenetML document.  They are currently loaded via a string that is calculated from the component class, with a command similar to
```import(`./renderers/${rendererType}.jsx`)```
For this reason, the files are not renamed by vite and old versions can continue to be cached even after they have updated.

How can we force new versions of those files to be loaded by the browser so that old versions don't cause crashes or other undefined behavior?   Can we manually rename the renderers directory so we don't have to deal with changing every file name?  Or is there a better solution that is built into vite?

**Comment by Lyanthropos** [comment]
As far as I can tell, the renderers are renamed in the assets folder. We can tell vite to include them explicitly.

<img width="305" alt="Screenshot 2023-04-25 at 15 17 14" src="https://user-images.githubusercontent.com/11381726/234393068-08438f01-9850-42b4-9456-435cab9cd325.png">

**Comment by jaltekruse** [comment]
@Lyanthropos I believe your proposed solution is to just use regular imports and not these lazily evaluated imports? I think making things work is a good first priority, so I'm not opposed, but if we were trying to preserve laziness I don't know how we do that in a way that vite would auto-resolve the names with the hashes in them.

**Comment by dqnykamp** [comment]
Could we use this [glob import](https://vitejs.dev/guide/features.html#glob-import) feature of vite to do the work for us?

**Comment by dqnykamp** [comment]
Looking at the Network tab on production, the renderers are loading with names like `graph-b30ca697.js`.  So maybe, there isn't a problem like I thought there was.  When I renamed the updateValue renderer, we would get errors that `updateValue.jsx` was undefined, but maybe that was just vite being smart and changing the error message to the original name?
