### ISSUE TITLE
Request: automatically convert a vector-value function of a single variable into a parametrized curve

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetTools#2152]
If we define a vector valued function of a single variable
```
<function name="g" variable="t">(t^2,t^3)</function>
```
then giving it as a child of a curve or putting it into a graph
```
<curve>$g</curve>
<graph>$g</curve>
```
should create a parametrized curve.  Currently, curve doesn't recognize it is a vector-valued function and creates a function curve based on its first component.

**Comment by rogness** [comment]
I ran into this issue when creating a parametric curve plotter.  (It's not yet completed, but I made it public for the convenience of this discussion: [public link](https://www.doenet.org/portfolioviewer/_W1tpDcryAgjPNCJV1rKMa).). I want the user to be able to enter the vector valued function and have it be graphed below.  I was pulling my hair out trying to get the user-defined function recognized inside of the `<curve>` tag, until I saw this issue.

You mentioned that you don't expose the component functions; my current workaround uses the fact that the components are exposed for vectors:

```
Function: <m>\vec{x}(t)=</m> <mathInput prefill="(2cos(t),sin(2t))" name="fnFormula"></mathinput>
 
<vector name="fVec">$fnFormula</vector>
<graph>
  <curve variable="t">
    ($fVec.x, $fVec.y)
  </curve>
</graph>
```

Given the differences between vectors and functions, I was a little surprised -- but glad -- that this works.  You could probably suggest a better way?

**Comment by dqnykamp** [comment]
This works because we have explicitly sugared a string with parentheses and a comma inside a curve to be separate functions.  I.e.,  `<curve variable="t">(t^2,t^3)</curve>` becomes 
```
<curve variable="t">
  <function>t^2</function>
  <function>t^3</function>
</curve>
```

You don't necessarily have to create a vector, as `<math>`s also have `x` and `y` properties if they happen to be vectors.  I didn't put `x` and `y` on a mathinput itself (maybe I should?) so you have to use the `value` property to get an explicit `math` out of the `mathinput`:
```
<curve variable="t">
  ($fnFormula.value.x, $fnFormula.value.y)
</curve>
```
I don't know that this is any better than your version.  One bug (or feature) is that `x` and `y` of `<math>` also work for lists, so it would still produce the graph is a student omitted the parentheses.
