### ISSUE TITLE
showCoordsWhenDragging="false" needs to work for line segments, circles, etc.

### ISSUE THREAD

**Issue by rogness** [Doenet/DoenetTools#2160]
(Deleting my initial message; at first we thought the bug had to do with < callAction >, but it's actually different; see title or next comment.)

**Comment by hsrisser** [comment]
We need to have line segments, circles, and other objects have the attribute "showCoordsWhenDragging" as well as the points.

**Comment by virginiaMae** [comment]
Note: This does currently work for lineSegments, if points are directly specified in the endpoints attribute. If points are references, then the attribute does not inherit the specification for the point. Both the point and the segment must have the "showCoordsWhenDragging" instance in that case. 
For circles, if rendering a center or throughPoint, then the point itself must have the "showCoordsWhenDragging" spec. If no points are rendered, then there are no coords shown, so it might not make sense to have the attribute on the `<circle/>.`  See example.[https://www.doenet.org/portfolioeditor/_HFR8UVnGJ5yKCJKpf55mD/_viMLHWchNC3as9J3UM84y](url)

**Comment by dqnykamp** [comment]
Note: PR #2230 adds showCoordsWhenDragging for vector, polygon, polyline, and curve.  It is only available for components that render built-in points.  For components like circle, line, or ray, no points are shown by the renderers themselves.  For these latter components, any points seen on the graph (like the center of a circle) are from outside points, and those outside points themselves can be given the showCoordsWhenDragging attribute.
