### ISSUE TITLE
This needs to be a little fixed:

### ISSUE THREAD

**Issue by bartsnapp** [Doenet/DoenetTools#2169]

**Comment by bartsnapp** [comment]
![image](https://github.com/Doenet/DoenetTools/assets/1376703/99d4b0bd-6b6b-4a25-8842-215cb2420ce9)


https://www.doenet.org/portfolioviewer/_qlwkKoR8UdpPz8fRX7Ux8

**Comment by rogness** [comment]
Agreed!  I couldn't replicate your picture but I'm assuming you were dragging points around?  (It was originally written as a quick demonstration of a multi-stage animation and I didn't spent time trying to break it before posting it publicly...)

I think I fixed it (literally) by adding "fixed" to all the <points>, but maybe you could double check by doing whatever you did before?

**Comment by dqnykamp** [comment]
@bartsnapp Is this fixed so we can close this issue?  Or is there more that still needs to be done?

**Comment by dqnykamp** [comment]
Going to assume this is fixed and am closing the issue.  Please reopen if there is more to be done.
