### ISSUE TITLE
boundaryValue starting at 0 for regionBetweenCurveXAxis not rendering correctly

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#2176]
`<graph size="small" xmin="-1" xmax="6">
  <function name="f">sqrt(x)</function>
  <regionBetweenCurveXAxis function="$f" boundaryValues="0 4"/>
</graph>`

**Comment by dqnykamp** [comment]
This appears to be due to a [bug in JSXGraph](https://github.com/jsxgraph/jsxgraph/issues/541).
