### ISSUE TITLE
Define Line through a point and perpendicular to another line (or line segment)

### ISSUE THREAD

**Issue by rogness** [Doenet/DoenetTools#2178]
Feature request: add the ability to define a line through P and perpendicular to another line/segement.

**Comment by rogness** [comment]
FWIW, here's a current workaround to create a line through point `$A` and perpendicular to line `$BC`.

> `<line equation="-$BC.coeffVar2*(x-$A.x)+$BC.coeffVar1*(y-$A.y)=0" />`

It would be nice to able to write

> `<line through="$A" perpendicularTo="$BC" />`

where `$BC` is a line or segment.

**Comment by dqnykamp** [comment]
Ended up creating both `parallelTo` and `perpendicularTo` attributes for a line, the latter which works only in 2D.  The attributes currently accept lines, line segments, vectors, rays, and mathematical expressions that are vectors.

**Comment by rogness** [comment]
Great!
