### ISSUE TITLE
In the ref component, uri="doenet:doenetID=..." specification should take you to portfolioviewer page

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#2207]
Currently, this specification will take you to a public link instead. A full url must be provided to navigate to the portfolioviewer page

**Comment by dqnykamp** [comment]
Yeah, please don't add the full url for the portfolio viewer, or else the DoenetML won't work in other contexts.  We need this fix so you can just use the regular `doenet:` uri!
