### ISSUE TITLE
Feature Request: viewerRatio controls relative viewer size in side-by-side mode of codeEditor

### ISSUE THREAD

**Issue by rogness** [Doenet/DoenetTools#2208]
I'm using a lot of `<codeEditor>` components in the tutorial, and I know this is an issue in the documentation as well.  Some of the code editors have very short snippets of code, which leaves lots of vertical whitespace on the page; see [this first page](https://www.doenet.org/portfolioviewer/_0FvPfhN5L9jAC0LvOTJiv), for example.  Conversely, some longer snippets (see "Multiple Answers" in [this page](https://www.doenet.org/portfolioviewer/_zBsoejaKgsPbHiLV1W3Z2)) don't fit in the code editor box, which makes it harder for the reader to see all of the code and study the example.  [That happens to me a _lot_ when reading the documentation.]

I think the default height is reasonable, but it would be nice to have some optional `showLines="20"` attribute (or whatever an appropriate name would be) to make the code editor shorter or taller, as appropriate.

Less important: when using `showResults` the editor and results are equal width.  That works well as the default, but there are times I wish I could adjust it (say, to 60/40) so that there would be less line wrapping in the indented code; again, wrapping makes it harder for the user to read.

**Comment by dqnykamp** [comment]
A `<codeEditor>` currently has both a `width` and a `height` attribute.  If `showResults` is set, then this width/height controls the combined editor and viewer.

There is a `viewerRatio` attribute (default 0.5) that controls which fraction of the combined object is the viewer.  However, it seems like this attribute does not work when the viewer is to the side (it only works when the results are at the bottom, which was the original arrangement we made).

**Comment by rogness** [comment]
I thought I had tried a heigh attribute, but clearly must not have, duh.  So maybe the answer is just to use height="600" (or whatever) and close this issue.  Do we have any sense of how robust that is from an accessibility point of view, i.e. zooming, or choosing a different font?  I'll freely admit that, with my aging eyes, I hit Control/Command-+ in Chrome at times to read small font.  I just added height="600" to a code editor, and it was enough to view 20 lines in the editor... but after hitting Command-+ twice, I could only see 13 lines.  Maybe that's unavoidable because of the way Chrome zooms.

Do you have a strong preference for where the results are shown in the tutorial?  I could switch to the bottom (which would definitely reduce issues with code wrapping, and allow `viewerRatio` to work).  Right now I have the results on the right, which is the exact opposite of the editor in course content or the portfolio.  I did that mostly to experiment, but there is a UI advantage.  The "update" button is in the upper left of the results, so if you edit code on the left, it's a shorter trip with the mouse cursor to update results.

**Comment by dqnykamp** [comment]
I'm not sure about how accessible our side-by-side code editor is.  In general, we will need auditing on accessibility to find ways we can improve.

I don't have a preference about the relative location of the viewer window.  On a larger display, I find it easier to see it when they are side-by-side.  Ideally, we should have responsive design so that it moves below on narrower screens.  Not sure about left versus right orientation.  We could have have "update" button move toward the right when the code viewer is at the left, though that would be inconsistent from our regular editor.

**Comment by dqnykamp** [comment]
For this github issue, we could turn it into a request for viewer ratio to work with side-by-side panels.  Or will folks demand that we have a moveable divider?
